### ISSUE TITLE
Add support for K8S Deployments

### ISSUE THREAD

**Issue by kop** [ployst/docker-letsencrypt#1]
Since Kubernetes v1.2.0, [Deployment](http://kubernetes.io/docs/user-guide/deployments/) is a recommended replacement for Replication Controllers. It would be great if this image added support for them.

**Comment by alexcouper** [comment]
@kop completely agree.

In terms of implementation, this image uses rolling update to gracefully replace all containers with containers that are identical (except they have the new secret loaded)

Deployments will require a different approach.

I'm thinking of having this image set an expected env var in given deployments container template of `LETS_ENCRYPT_UPDATED` with the date it was run. This will then kick off a replacement of running containers and thus a cert refresh.

If you see any issues with this approach, feel free to chime in.

**Comment by kop** [comment]
@alexcouper, to be honest, I'm not sure I'm following.

How this `LETS_ENCRYPT_UPDATED` variable will be managed? And by whom? And how do you plan to update containers in Deployment? Just by killing them?

**Comment by kop** [comment]
I've spent some time to read relative discussions (about secrets and configMaps updates) in Kubernetes issue tracker. It seems that the only "true" way of doing this is:

> To do a rolling update of a ConfigMap, the user needs to create a new ConfigMap, update a Deployment to refer to it, and delete the old ConfigMap once no pods are using it.

I'm not sure that this image should really implement this. Maybe it makes sense to wait until some decisions in Kubernetes will be made about live `Secret` reloads.

**Comment by alexcouper** [comment]
@kop let me explain what I'm thinking.

Given a deployment like this:

``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - env:
        - name: SOME_ENV_VAR
          value: this
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

If I make a change to spec.template, and reapply, the deployment object will check if the corresponding replica set is managing containers that look like this template.

If they're not it will create a new replica set in a rolling update. If they're identical it will do nothing.

What this means is that I need to somehow get spec.template to look different in the deployment object. So what I'm planning on is this letsencrypt image doing that.

From the end user's perspective you'll set up an image of letsencrypt with a new env var, replacing the current `RC_NAMES`, of `DEPLOYMENTS`. It is a list of deployment names whose pods should be restarted after a cert upgrade.

What will happen in [recreate_pods](https://github.com/ployst/docker-letsencrypt/blob/master/recreate_pods.sh) is that rather than performing a `kubectl rolling-update` on the RC_NAMES, it will patch the `DEPLOYMENTS` given with a new spec.template.spec.containers.env with a `LETSENCRYPT_CERT_REFRESH` variable with the value of the current date.

The deployment will then look at the current replica set and realise that it needs to perform an update, and it will kick off a rolling update of the pods (by creating a new replica set and slowly upping the number it has whilst reducing the current number).

All the new pods will then have the correct cert.

Make sense?
