### ISSUE TITLE
no crontab for root

### ISSUE THREAD

**Issue by devth** [ployst/docker-letsencrypt#7]
In the logs I see:

```
no crontab for root
```

on startup. Using `ployst/docker-letsencrypt:0.0.7`. Is that benign?

**Comment by alexcouper** [comment]
I at least don't see it. Assuming you're in k8s, could you paste your deployment/rc that manages it.

If you do `exec /bin/bash` on the pod and run `crontab -l` what do you see?

**Comment by devth** [comment]
``` yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: letsencrypt
spec:
  replicas: 1
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
        teir: infra
    spec:
      containers:
      - name: letsencrypt
        image: ployst/letsencrypt:0.0.7
        env:
        # use staging endpoint while testing
        - name: LETSENCRYPT_ENDPOINT
          value: https://acme-staging.api.letsencrypt.org/directory
        - name: EMAIL
          value: foo@bar.com
        - name: DOMAINS
          value: foo.com
        - name: SECRET_NAME
          value: letsencrypt
        # - name: DEPLOYMENTS
        #   value: nginx-ssl-proxy-api
        ports:
        - name: ssl-proxy-http
          containerPort: 80
```

`crontab -l` shows:

```
52 21 1 * * PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin KUBERNETES_PORT=tcp://10.95.240.1:443 KUBERNETES_PORT_443_TCP_PORT=443 KUBERNETES_SERVICE_PORT=443 KUBERNETES_SERVICE_HOST=10.95.240.1 KUBERNETES_PORT_443_TCP_PROTO=tcp KUBERNETES_PORT_443_TCP_ADDR=10.95.240.1 KUBERNETES_PORT_443_TCP=tcp://10.95.240.1:443 SECRET_NAME=... DEPLOYMENTS='' DOMAINS='...' EMAIL=... /bin/bash /letsencrypt/refresh_certs.sh >> /var/log/cron-encrypt.log 2>&1
```
